version: '3'

services:
  db:
    image: postgres
  migration:
    build: .
      command: python3 manage.py migrate
      volumes:
        - .:/home/jim/Tjs/Docke
      depends_on:
        - db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/home/jim/Tjs/Docke
    ports:
      - "8080:8000"
    depends_on:
      - db
      - migration